// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvkdgbletxpjgqlowyjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a2RnYmxldHhwamdxbG93eWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTg4ODcsImV4cCI6MjA2NDAzNDg4N30.yJIPkIiWBYuWmDLV7tYkiJkqJw_dCt8OCxQZZ0sHc9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);